### ISSUE TITLE
[docker] docker-compose file seems outdated

### ISSUE THREAD

**Issue by vchrombie** [Bitergia/prosoul#214]
I was trying to test the docker-compose solution, but it has turned out showing some error 
```
Unsupported config option for prosoul: 'depends_on'
```

I changed the format of the `docker-compose.yml` and it worked perfectly fine.
```
version: '2'

services:
    elasticsearch:
      image: bitergia/elasticsearch:6.1.0
      command: /elasticsearch/bin/elasticsearch -E network.bind_host=0.0.0.0
      ports:
        - "9200:9200"
      environment:
        - ES_JAVA_OPTS=-Xms2g -Xmx2g

    kibiter:
      image: bitergia/kibiter:6.1.0-optimized
      links:
        - elasticsearch
      ports:
       - "5601:5601"

    prosoul:
      image: bitergia/prosoul
      ports:
       - "8000:8000"
      depends_on:
       - kibiter
       - elasticsearch
      environment:
       - ALLOWED_HOSTS=prosoul localhost 127.0.0.1
       - ES_URL=https://admin:admin@elasticsearch:9200
       - KIBITER_URL=https://kibiter:80
```

Also, do you think we should update the `elasticsearch` and `kibiter` configurations to ES/Kibiter 6.8?
